language: rust
cache: cargo
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev # needed only for `--verify` coveralls flag
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  (cargo install rustfmt --force || true) &&
  export PATH=$HOME/.local/bin:$PATH &&
  export PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
after_success:
- travis-cargo coveralls --no-sudo --verify
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/stream-*; fi
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: Yp1m4IszU9Xkhf7e4F2/zHnE5BLmivlyzIghaksOanbzOzeXrSkau8wwBlPlqcqL/BhBmkxBt3mRIVkurpJ/UbNKhKu7Bowr5x/MP6CceX62iA9fz45dsQ0em0Srmsf2TGKLDBA7mHJwNYevgxpVB7ajBqAUNpajqm7ZUCcZZ/T41yXxzvokZUZcc7YFvWW0g+4p/rQ6oZowQB7ylpo9EOi2UZkeOJ2cFHVoxHtva8XdnZeHhTY4cIMkt5tg3j3Tp+R7e9itgbq1RrU1U9DnhBh4syBFw64/EoUuCMh2kfh/Xewh8vlmBH2rpHp+LMVBSevXUCOMBqU6G2xDuA9SmTXf/y4WDQ1OrSPDFeNXIiRp05KUNTIj/DLXYujKwXzIE4DVccn31CRe6t2q0jShRrQAwBaDgP2EnyZnQ4WDaqhz+TjUwU5ZXrHdaHN29aQX3Tc3g/bZBAFEZ7wdvyc4/GEBiU6ezpd3afVneidxsBeZS6LD2R4rtJhD8XPw9d3J9lPmB04v2u3uoqM4Tqd7sO+rzqpSFpPJVgJ4Ehq54e7GR20y1K7Tp/edLdvAbJ99UwO7NKaLYuvXyCZfUyEXo05o3teW4X+cfiQ/If1fs+m+QA1Fkrx8EvxBogtNo6qaH/dkZd/mXbvbcBoUC3OozegDulS1IdYcCNOTncr9rlY=
