language: rust

rust:
    - nightly

script:
- |
    (cd tarpc && travis-cargo build) &&
    (cd tarpc && travis-cargo test)

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""